# use the following command to run this script:
# ansible-playbook -i hosts.ini playbook.yml -e "youtube_url=https://your-youtube-url"

- hosts: localhost
  gather_facts: no
  vars:
    instance_id: 'your_instance_id'

  tasks:
    - name: Start EC2 instance
      amazon.aws.ec2:
        instance_ids: "{{ instance_id }}"
        state: running
        wait: yes
      register: ec2_info

- hosts: "{{ ec2_info.instances[0].public_ip }}"
  gather_facts: no

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes

    - name: Install Python3
      ansible.builtin.apt:
        name: python3
        state: present
      become: yes

    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip
        state: present
      become: yes

    - name: Install necessary Python packages
      ansible.builtin.pip:
        name:
          - youtube_dl
          - requests
          - boto3
        executable: pip3
      become: yes

    - name: Copy script to remote
      ansible.builtin.copy:
        src: /path/to/your/script.py
        dest: /home/ubuntu/

        # Remember to change the name of the script here if necessary!
    - name: Run script
      ansible.builtin.shell: python3 /home/ubuntu/script.py "{{ youtube_url }}"
      args:
        executable: /bin/bash
      register: script_output

    - name: Print script output
      ansible.builtin.debug:
        var: script_output.stdout_lines

- hosts: localhost
  gather_facts: no
  vars:
    instance_id: 'your_instance_id'

  tasks:
    - name: Stop EC2 instance
      amazon.aws.ec2:
        instance_ids: "{{ instance_id }}"
        state: stopped

