name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test
      run: |
        output=$(go test -v ./... 2>&1)
        echo "$output"
        exit 1

    - name: Notify Discord on Failure
      if: failure()
      run: |
        COMMITTER_GITHUB=$(git show -s --format='%cn')
  
        case "$COMMITTER_GITHUB" in
          "kings177")
            DISCORD_ID="353453210389839872"
            ;;
        #   "test")
        #     DISCORD_ID="353453210389839872"
        #     ;;
          *)
            DISCORD_ID=""
            ;;
        esac
        
        CI_LINK="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        if [ ! -z "$DISCORD_ID" ]; then
          SHORTENED_LOG=$(echo "$LOG" | tail -c 1900)
          MESSAGE="<@$DISCORD_ID> , CI Failed, Error log:\n\`\`\`\n$SHORTENED_LOG\n\`\`\`\n please check: $CI_LINK"
          curl -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "content": "'"$MESSAGE"'",
              "username": "Kindelia Bot"
            }'
        else
          echo "Commit Owner not part of the Kindelia Team. CI failed: "
        fi
