name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Your CI steps go here...
    - name: Test
      run: |
        # Replace this with your actual test or build commands.
        exit 1 # This simulates a failure. Remove this.

    - name: Notify Discord on Failure
      if: failure()
      run: |
        COMMITTER_GITHUB=$(git show -s --format='%cn')
        
        # Mapping from GitHub to Discord handles
        case "$COMMITTER_GITHUB" in
          "kings177")
            DISCORD_HANDLE="kingu0"
            ;;
        #   "test")
        #     DISCORD_HANDLE="kingu0"
        #     ;;
          *)
            DISCORD_HANDLE=""
            ;;
        esac
        
        CI_LINK="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        if [ ! -z "$DISCORD_HANDLE" ]; then
          MESSAGE="@$DISCORD_HANDLE , CI Failed, please check: $CI_LINK"
          curl -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "content": "'"$MESSAGE"'",
              "username": "Kindelia Bot"
            }'
        else
          echo "Commit Owner not part of the Kindelia Team. CI failed: ."
        fi
